### ISSUE TITLE
Maven 3.1.1 requirement?

### ISSUE THREAD

**Issue by mondain** [grgrzybek/tomcat-slf4j-logback#55]
I'm using Maven 3.0.5 and I cannot build your latest source, I am seeing this issue:
```
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-enforcer-plugin:1.3.1, parent: sun.misc.Launcher$AppClassLoader@32edeea8]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce' with basic configurator -->
[DEBUG]   (s) fail = true
[DEBUG]   (s) failFast = false
[DEBUG]   (f) ignoreCache = false
[DEBUG]   (s) version = [3.1.1,)
[DEBUG]   (s) rules = [org.apache.maven.plugins.enforcer.RequireMavenVersion@5d0e47b3]
[DEBUG]   (s) skip = false
[DEBUG]   (s) project = MavenProject: org.grgrzybek:tomcat-slf4j-logback:1.1.0 @ /home/mondain/workspace/github/tomcat-slf4j-logback/pom.xml
[DEBUG]   (s) session = org.apache.maven.execution.MavenSession@28f9533
[DEBUG] -- end configuration --
[DEBUG] Executing rule: org.apache.maven.plugins.enforcer.RequireMavenVersion
[DEBUG] Rule org.apache.maven.plugins.enforcer.RequireMavenVersion is cacheable.
[DEBUG] Detected Maven Version: 3.0.5
[DEBUG] Adding failure due to exception
org.apache.maven.enforcer.rule.api.EnforcerRuleException: Detected Maven Version: 3.0.5 is not in the allowed range [3.1.1,).
	at org.apache.maven.plugins.enforcer.AbstractVersionEnforcer.enforceVersion(AbstractVersionEnforcer.java:106)
	at org.apache.maven.plugins.enforcer.RequireMavenVersion.execute(RequireMavenVersion.java:51)
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.0.5 is not in the allowed range [3.1.1,).

```

**Comment by hazendaz** [comment]
You can switch your fork pom references from 3.1.1 back to 3.0.5 and it should then build ok for you.  Alternatively you can grab any of builds from source forge or update maven if you can.  While the build doesn't require that high of maven version we are trying to move forwards.  Optionally if it might help we could start pushing the resulting jar to maven central.  Let me know what might help best.

--- Original Message ---

**Comment by hazendaz** [comment]
Closing issue.  It's been a few months and majority of online tools for building projects like travis ci are much farther ahead now.  As noted previously, we are not strictly tied to newer versions and if building on your own you can switch back without issue.  Preferrably though, it is best to use more recent versions.
